- docs/config.json
- docs/framework/vue/quick-start.md
- docs/framework/vue/reference/useStore.md
- docs/installation.md
This PR adds the initial docs for the Vue package. The rest should be filled in over time
> docs: scaffold initial todo Vue docs

- docs/framework/react/reference/useStore.md
This PR add the useStore react hook reference docs and explains the hook API.
> docs(useStore): add react docs

- docs/reference/Store.md
This PR write the API docs of Store. 
Issue: https://github.com/TanStack/store/issues/7
> docs(store): add store docs

- packages/react-store/src/__tests__/index.test.tsx
- packages/vue-store/src/__tests__/index.test.tsx
This PR adds tests to cover `shallow` function on both `react` and `vue` adapters.
> test(react-store,vue-store): add test for shallow function on both react/vue adapters

- packages/store/src/index.ts
This PR removes the unused `priority` from all code on the store core package. This should reduce bundle size and remove some confusion around the usage of store.
> chore!: remove priority from store to reduce bundle size

- docs/config.json
- docs/framework/angular/quick-start.md
- docs/framework/angular/reference/injectStore.md
- docs/installation.md
- docs/overview.md
- package.json
- packages/angular-store/.eslintrc.cjs
- packages/angular-store/package.json
- packages/angular-store/src/index.ts
- packages/angular-store/src/tests/index.test.tsx
- packages/angular-store/src/tests/test-setup.ts
- packages/angular-store/tsconfig.json
- packages/angular-store/tsconfig.legacy.json
- packages/angular-store/vite.config.ts
- pnpm-lock.yaml
This PR adds Angular implementation
- Only v16+ is supported because of Signals
> feat: add angular store

- .github/workflows/pr.yml
- .gitignore
- .nx/workflows/dynamic-changesets.yaml
- nx.json
See here: https://github.com/TanStack/query/pull/6863
> ci: Add Nx agents

- .github/workflows/ci.yml
- .github/workflows/pr.yml
This may not work depending on if cached outputs get downloaded by the GitHub workflow.
> ci: Run Nx Agents on `ci.yml`

- package.json
- packages/angular-store/tsconfig.json
- packages/angular-store/tsconfig.legacy.json
- packages/react-store/tsconfig.json
- packages/react-store/tsconfig.legacy.json
- packages/solid-store/tsconfig.json
- packages/solid-store/tsconfig.legacy.json
- packages/vue-store/tsconfig.json
- packages/vue-store/tsconfig.legacy.json
- pnpm-lock.yaml
- tsconfig.json
- "Go to source" will now take you to the source `.ts` rather than the dist `.js` or `.d.ts`
- Can run project tasks (e.g. test react-store) without needing dependencies (i.e. store) to be built first
- Root tsconfig copied from form (some fields were redundant since tsc is not used to generate build/types)
- Related PR: https://github.com/TanStack/form/pull/617
> chore: Use tsconfig paths to improve local DX

- packages/react-store/package.json
- packages/solid-store/package.json
- packages/vue-store/package.json
This PR fixes the old rep link in npm
> Fix repo link in npm

- .npmrc
- Default setting changed to false in pnpm v9
- Fixes local development of examples
> chore: Enable link-workspace-packages

- .eslintrc.cjs
- package.json
- packages/react-store/.eslintrc.cjs
- packages/react-store/src/tests/index.test.tsx
- pnpm-lock.yaml
- Replace eslint-plugin-react (107 deps) with @eslint-react/eslint-plugin (56 deps)
- Replace eslint-plugin-import (95 deps) with eslint-plugin-import-x (52 deps)
- Both of these new plugins are eslint v8 and v9 compatible, and are adopted by [@antfu/eslint-config](https://github.com/antfu/eslint-config)
- Remove eslint-import-resolver-typescript (typescript already reports unresolved imports and with greater accuracy)
> chore: Replace ESLint plugins

- .browserslistrc
This was added in the initial commit for this repo, and wasn't removed (i.e. I missed it) when babel/rollup were replaced with vite
> chore: Remove browserslistrc

- packages/angular-store/package.json
- packages/react-store/package.json
- packages/solid-store/package.json
- packages/store/package.json
- packages/svelte-store/package.json
- packages/vue-store/package.json
- The `"repository"` field is supposed to be an object as described here: https://docs.npmjs.com/cli/v10/configuring-npm/package-json#repository
- `"publishConfig"` was removed as it is unnecessary (npm is the default registry)
- I've also re-arranged the properties for consistency, and added a description from the website
- This fix is required for an exciting change I will work on tomorrow... watch this space!
> fix: Add correct `"repository"` field to `package.json`

- package.json
- pnpm-lock.yaml
Prettier v4 alpha maintenance has dramatically slowed, and the latest alpha (alpha.9) is currently broken in GitHub Actions (https://github.com/prettier/prettier-cli/issues/14). It also doesn't format code identically to v3 as it is behind on some rules.
The speed benefit is nice, but not really noticeable on CI (where Nx agent startup time is the main limiting factor).
> chore(deps): Use prettier v3.3.3

- packages/angular-store/package.json
Users on Angular 18 currently need to force override peer dependency restriction. This changes the range to match that used by `@tanstack/angular-query-experimental`.
> fix(angular): update peerDependencies range

- packages/store/src/derived.ts
- packages/store/tests/derived.test.ts
> This PR builds on top of #40, please merge that first
This PR adds in a lazyness option to the derived class that:
- Doesn't update a value until it's needed
- Still works when other items are derived from _it_
> feat: add lazyness to derived

- docs/quick-start.md
the state was not read from the correct variable
> Fix typo in quickstart guide

- docs/framework/angular/quick-start.md
- docs/framework/react/quick-start.md
- docs/framework/solid/quick-start.md
- docs/framework/svelte/quick-start.md
- docs/framework/vue/quick-start.md
- examples/angular/simple/angular.json
- examples/angular/simple/package.json
- examples/angular/simple/src/app/store.ts
- examples/react/simple/package.json
- examples/react/simple/src/index.tsx
- examples/solid/simple/package.json
- examples/solid/simple/src/index.tsx
- examples/svelte/simple/package.json
- examples/svelte/simple/src/store.ts
- examples/vue/simple/package.json
- examples/vue/simple/src/store.ts
- pnpm-lock.yaml
- vitest.workspace.ts
Import Store from framework adpaters.
Add react-scan to react example
Add vite workspace for IDEs to be able to pick up vitest unit tests
> examples(all): remove core store from examples and add react-scan to react example

- docs/quick-start.md
`updateValue` is a function so can not return function + number. If it's not expected behaviour then we need to fix library.
> Fixed updateFn doc

- docs/reference/functions/batch.md
- packages/store/src/scheduler.ts
- packages/store/src/types.ts
If we're ok w/ sending the exact same object to all listeners, instead of 1 new object per listener, we can get much better performance out of the `__notifyListeners` and `__notifyDerivedListeners` methods.
To reflect that it's now a single object, the `ListenerValue` is also updated to be `readonly` to indicate that it should not be mutated by the client.
These functions are already lightweight, but they're also in the hot-path (called a lot when a lot of things are happening) so any gain should be considered in my opinion.
---
Benchmark (tl;dr 3x)
```ts
describe('Scheduler notifyListeners', () => {
const store: Store<unknown> = {
listeners: new Set(Array.from({ length: 100 }, () => () => { })),
prevState: {},
state: {},
}
bench('old', () => {
__notifyListenersOld(store)
})
bench('new', …
```
> refactor(store): scheduler __notifyListeners performance

- packages/store/src/scheduler.ts
This is a very minor change, but it's more performant to access the 1st item of a set going through its iterator methods than by deriving an array from it and then reading the 1st value. (Plus as a bonus, types are correct and we don't need the `as` anymore)
---
benchmark (tl;dr 1.3x)
```ts
describe('First of set', () => {
const set = new Set([1, 2, 3, 4, 5])
bench('old: Array.from(set)[0]', () => {
const first = Array.from(set)[0]
})
bench('new: set.values().next().value', () => {
const first = set.values().next().value
})
})
```
```sh
✓  @tanstack/store  tests/scheduler.bench.ts > First of set 10142ms
name                                       hz     min     max    mean     p75     p99    p995    p999     rme   samples
· old: Array.from(set)[0]         34,766,506.82  0.0000  0.0557 …
```
> refactor(store): scheduler batch finalization performance
